### PR TITLE
Fix finding the correct body parameter for the request schema

### PR DESCRIPTION
**Pull request by tokarls**

### CODE REVIEW

**Comment by kibertoad** [comment]
Could you clarify which particular case does this fix?

**Comment by tokarls** [comment]
It fixes #26 which was closed prematurely.

**Comment by kibertoad** [comment]
@gargol Any chance you could check PRs this weekend? Thanks!

**Comment by gargol** [comment]
Merged in dd2336e86b75b5fc6b5dedc4e0b8dba97fc107b9. Thanks for contribution @tokarls! And thanks for paitence @kibertoad ;)

**Comment by kibertoad** [comment]
@gargol No problem, thank you very much for taking care of this! By the way, going forward, considering the limited amount of time that you have for this project, would you be open to either transferring the project to adidas corporation (https://github.com/adidas & https://www.npmjs.com/~adidas) so that we could officially maintain the project, or at least granting maintainer and publishing permissions to one of our developers, so that we could keep the momentum going :)?

**Comment by gargol** [comment]
> granting maintainer and publishing permissions to one of our developers

Yes, @kibertoad would totally be up for that :+1: DM me and we could discuss the details :)

**Comment by kibertoad** [comment]
@gargol Appreciate it! Pinged you on gitter.

**Pull request closed without merging**
