### PR TITLE
Feature/validate request and response

### PR DESCRIPTION
**Pull request by iadknet**
I noticed that if both `validateRequest` and `validateResponse` were enabled at the same time, validateResponse was never called.

This fixes that logic and adds some extra tests with both enabled.

### CODE REVIEW

**Comment by gargol** [comment]
Seems good. Will try to find some time tomorrow and test it in the other apps I'm using this middleware in. If you could sqash these changes into one commit with the convention I described in the other [PR](https://github.com/gargol/swagger-express-validator/pull/4#issuecomment-310497009), would merge it right after testing. Thanks!

**Comment by iadknet** [comment]
Will do, thanks for the great project!  I've been looking for something that will help enable the adoption of spec driven development in our organization for a while.

**Comment by iadknet** [comment]
Eslint ignores eliminated :)

**Comment by gargol** [comment]
merged in changes with 281007a06ab13221ca538987a033e55136a04a67

**Pull request closed without merging**
